"""initial table version

Revision ID: aa1ecb889f33
Revises: 
Create Date: 2018-07-29 22:41:47.495188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa1ecb889f33'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devicetype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=30), nullable=True),
    sa.Column('model', sa.String(length=30), nullable=True),
    sa.Column('netmiko_cat', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devicetype_brand'), 'devicetype', ['brand'], unique=False)
    op.create_index(op.f('ix_devicetype_model'), 'devicetype', ['model'], unique=False)
    op.create_index(op.f('ix_devicetype_netmiko_cat'), 'devicetype', ['netmiko_cat'], unique=False)
    op.create_table('host',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=64), nullable=True),
    sa.Column('ipv4_addr', sa.String(length=15), nullable=True),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('ios_type', sa.String(length=15), nullable=True),
    sa.Column('local_creds', sa.Boolean(), nullable=True),
    sa.Column('devicetype_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['devicetype_id'], ['devicetype.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_host_hostname'), 'host', ['hostname'], unique=True)
    op.create_index(op.f('ix_host_ios_type'), 'host', ['ios_type'], unique=False)
    op.create_index(op.f('ix_host_ipv4_addr'), 'host', ['ipv4_addr'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_host_ipv4_addr'), table_name='host')
    op.drop_index(op.f('ix_host_ios_type'), table_name='host')
    op.drop_index(op.f('ix_host_hostname'), table_name='host')
    op.drop_table('host')
    op.drop_index(op.f('ix_devicetype_netmiko_cat'), table_name='devicetype')
    op.drop_index(op.f('ix_devicetype_model'), table_name='devicetype')
    op.drop_index(op.f('ix_devicetype_brand'), table_name='devicetype')
    op.drop_table('devicetype')
    # ### end Alembic commands ###
